# Generated by Django 5.2 on 2025-05-03 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('idJuego', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del juego')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre del juego')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='descripcion del juego')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio del juego')),
                ('image', models.CharField(max_length=100, verbose_name='direccion de la portada del juego')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='juegos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalagos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=60, verbose_name='nombre completo del usuario')),
                ('nombreUsuario', models.CharField(max_length=60, verbose_name='Alias del usuario')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='correo personal')),
                ('clave', models.CharField(max_length=128, verbose_name='password')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(max_length=300, verbose_name='direccion')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca Vehixulo')),
                ('modelo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalagos.categoria')),
            ],
        ),
    ]
