# Generated by Django 5.2 on 2025-05-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalagos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
